fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
