###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: question-api-memcached

    mailhog:
      image: mailhog/mailhog:latest
      container_name: question-api-mailhog
      ports:
        - "8081:8025"

    redis:
      image: redis:alpine
      container_name: question-api-redis

    mariadb:
      image: mariadb:10.1
      container_name: question-api-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=question
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "8083:3306"

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: question-api-elasticsearch

    webserver:
      image: nginx:alpine
      container_name: question-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: question-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

